name: Release

on:
  push:
    tags:
        - 'v*' 

jobs:
  release:

    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Compile with pyinstaller
      run: |
        pip install pyinstaller
        pyinstaller --onefile genealogy_scrapper.py
        mkdir dist_release
        cp dist/* dist_release/  # Copy files to a release folder

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: "Automatically generated release"
        draft: false
        prerelease: false
        files: dist_release/*  # Attach built files

